import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import {
  Users,
  Plus,
  Search,
  Edit,
  Trash2,
  ExternalLink,
  Loader2,
  X,
  Upload,
  Check,
  Music,
  Drama,
  Laugh,
  Star,
  Languages,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import {
  usePerformers,
  useCreatePerformer,
  useUpdatePerformer,
  useDeletePerformer,
  generateSlug,
  type Performer,
  type PerformerInput,
} from "@/hooks/usePerformers";

// ============================================
// 💾 LOCAL STORAGE KEYS
// ============================================
const STORAGE_KEYS = {
  FORM_DATA: "admin_performers_form_data",
  SEARCH_QUERY: "admin_performers_search",
  EDITING_PERFORMER: "admin_performers_editing",
  MODAL_OPEN: "admin_performers_modal_open",
};

// ============================================
// 🌐 FUNKCIJA ZA PREVOD IZVOĐAČA
// ============================================
const translatePerformer = async (performerId: number | string): Promise<boolean> => {
  try {
    console.log(`🌐 Pokrećem prevod za izvođača ID: ${performerId}`);

    const { data, error } = await supabase.functions.invoke("translate-performers", {
      body: { performer_id: performerId },
    });

    if (error) {
      console.error("❌ Greška pri prevodu izvođača:", error);
      return false;
    }

    console.log("✅ Prevod izvođača uspješan:", data);
    return true;
  } catch (err) {
    console.error("❌ Prevod izvođača nije uspio:", err);
    return false;
  }
};

// Tipovi izvođača
const PERFORMER_TYPES = [
  { value: "Pjevač", label: "Pjevač", icon: Music },
  { value: "Pjevačica", label: "Pjevačica", icon: Music },
  { value: "Glumac", label: "Glumac", icon: Drama },
  { value: "Glumica", label: "Glumica", icon: Drama },
  { value: "Stand Up komičar", label: "Stand Up komičar", icon: Laugh },
  { value: "Bend", label: "Bend", icon: Music },
  { value: "Grupa", label: "Grupa", icon: Music },
  { value: "DJ", label: "DJ", icon: Music },
  { value: "Izvođač", label: "Izvođač (ostalo)", icon: Star },
];

// Helper za dobijanje ikonice po tipu
const getTypeIcon = (type?: string) => {
  const normalized = (type || "").toLowerCase();
  if (normalized.includes("glumac") || normalized.includes("glumica")) return Drama;
  if (normalized.includes("stand up") || normalized.includes("komičar")) return Laugh;
  if (
    normalized.includes("pjevač") ||
    normalized.includes("pjevačica") ||
    normalized.includes("pevač") ||
    normalized.includes("pevačica")
  )
    return Music;
  if (normalized.includes("bend") || normalized.includes("grupa") || normalized.includes("dj")) return Music;
  return Star;
};

/** ---------- AUTO SEO HELPERS (etickets-first) ---------- */
const buildPerformerSeoTitle = (name: string) => {
  const n = (name || "").trim();
  if (!n) return "";
  return `${n} koncerti i etickets – kupi karte online | etickets`;
};

const buildPerformerSeoDescription = (name: string) => {
  const n = (name || "").trim();
  if (!n) return "";
  return `Pronađi i kupi etickets za koncerte ${n} u Crnoj Gori i regionu. Brza online prodaja ulaznica, sigurno plaćanje i dostupne karte na etickets platformi.`;
};

/** Legacy (previous auto-generated format) - keep for detection only */
const buildPerformerSeoTitleLegacy = (name: string) => {
  const n = (name || "").trim();
  if (!n) return "";
  return `${n} koncerti i etickets – kupi karte online | etickets.me`;
};

const buildPerformerSeoDescriptionLegacy = (name: string) => {
  const n = (name || "").trim();
  if (!n) return "";
  return `Pronađi i kupi etickets za koncerte ${n} u Crnoj Gori i regionu. Brza online prodaja ulaznica, sigurno plaćanje i dostupne karte na etickets.me.`;
};

/** Helper: detect if current SEO fields look auto-generated for previous name */
const isAutoGeneratedTitle = (currentTitle: string, prevName: string) => {
  const ct = (currentTitle || "").trim();
  return ct === buildPerformerSeoTitle(prevName || "") || ct === buildPerformerSeoTitleLegacy(prevName || "");
};

const isAutoGeneratedDesc = (currentDesc: string, prevName: string) => {
  const cd = (currentDesc || "").trim();
  return (
    cd === buildPerformerSeoDescription(prevName || "") || cd === buildPerformerSeoDescriptionLegacy(prevName || "")
  );
};

// ============================================
// 💾 LOCAL STORAGE HELPERS
// ============================================
const saveToLocalStorage = (key: string, data: any) => {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (error) {
    console.error("Error saving to localStorage:", error);
  }
};

const loadFromLocalStorage = <T,>(key: string, defaultValue: T): T => {
  try {
    const item = localStorage.getItem(key);
    return item ? JSON.parse(item) : defaultValue;
  } catch (error) {
    console.error("Error loading from localStorage:", error);
    return defaultValue;
  }
};

const clearFromLocalStorage = (key: string) => {
  try {
    localStorage.removeItem(key);
  } catch (error) {
    console.error("Error clearing from localStorage:", error);
  }
};

const AdminPerformers = () => {
  // 💾 Load initial state from localStorage
  const [searchQuery, setSearchQuery] = useState(() => loadFromLocalStorage(STORAGE_KEYS.SEARCH_QUERY, ""));

  const [isModalOpen, setIsModalOpen] = useState(() => loadFromLocalStorage(STORAGE_KEYS.MODAL_OPEN, false));
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);

  const [editingPerformer, setEditingPerformer] = useState<Performer | null>(() =>
    loadFromLocalStorage(STORAGE_KEYS.EDITING_PERFORMER, null),
  );

  const [deletingPerformer, setDeletingPerformer] = useState<Performer | null>(null);
  const [isTranslating, setIsTranslating] = useState(false);

  const [formData, setFormData] = useState<PerformerInput>(() =>
    loadFromLocalStorage(STORAGE_KEYS.FORM_DATA, {
      name: "",
      slug: "",
      biography: "",
      image: "",
      type: "Izvođač",
      seo_title: "",
      seo_description: "",
    }),
  );

  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isUploadingImage, setIsUploadingImage] = useState(false);

  const { data: performers = [], isLoading } = usePerformers();
  const createMutation = useCreatePerformer();
  const updateMutation = useUpdatePerformer();
  const deleteMutation = useDeletePerformer();

  // ============================================
  // 💾 SAVE TO LOCALSTORAGE ON CHANGES
  // ============================================
  useEffect(() => {
    saveToLocalStorage(STORAGE_KEYS.SEARCH_QUERY, searchQuery);
  }, [searchQuery]);

  useEffect(() => {
    saveToLocalStorage(STORAGE_KEYS.FORM_DATA, formData);
  }, [formData]);

  useEffect(() => {
    saveToLocalStorage(STORAGE_KEYS.EDITING_PERFORMER, editingPerformer);
  }, [editingPerformer]);

  useEffect(() => {
    saveToLocalStorage(STORAGE_KEYS.MODAL_OPEN, isModalOpen);
  }, [isModalOpen]);

  const filteredPerformers = performers.filter((p) => p.name.toLowerCase().includes(searchQuery.toLowerCase()));

  const handleOpenCreate = () => {
    setEditingPerformer(null);
    clearFromLocalStorage(STORAGE_KEYS.EDITING_PERFORMER);

    const newFormData = {
      name: "",
      slug: "",
      biography: "",
      image: "",
      type: "Izvođač",
      seo_title: "",
      seo_description: "",
    };

    setFormData(newFormData);
    setImagePreview(null);
    saveToLocalStorage(STORAGE_KEYS.FORM_DATA, newFormData);
    setIsModalOpen(true);
  };

  const handleOpenEdit = (performer: Performer) => {
    setEditingPerformer(performer);

    const editFormData = {
      name: performer.name,
      slug: performer.slug,
      biography: performer.biography || "",
      image: performer.image || "",
      type: performer.type || "Izvođač",
      seo_title: performer.seo_title || "",
      seo_description: performer.seo_description || "",
    };

    setFormData(editFormData);
    setImagePreview(performer.image || null);
    saveToLocalStorage(STORAGE_KEYS.FORM_DATA, editFormData);
    saveToLocalStorage(STORAGE_KEYS.EDITING_PERFORMER, performer);
    setIsModalOpen(true);
  };

  const handleOpenDelete = (performer: Performer) => {
    setDeletingPerformer(performer);
    setIsDeleteDialogOpen(true);
  };

  // ============================================
  // 🖼️ IMAGE FILE UPLOAD
  // ============================================
  const handleImageFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) {
      toast({ title: "Greška", description: "Slika mora biti manja od 5MB", variant: "destructive" });
      return;
    }
    if (!["image/jpeg", "image/png", "image/webp", "image/gif"].includes(file.type)) {
      toast({ title: "Greška", description: "Dozvoljeni formati: JPG, PNG, WebP, GIF", variant: "destructive" });
      return;
    }
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = reader.result as string;
      setImagePreview(base64);
      setFormData((prev) => ({ ...prev, image: "" }));
    };
    reader.readAsDataURL(file);
  };

  const base64ToFile = async (base64: string, filename: string): Promise<File> => {
    const res = await fetch(base64);
    const blob = await res.blob();
    return new File([blob], filename, { type: blob.type });
  };

  const uploadPerformerImage = async (slug: string): Promise<string | null> => {
    // Existing URL
    if (formData.image && formData.image.startsWith("http")) return formData.image;
    // Base64 file upload
    if (imagePreview && imagePreview.startsWith("data:")) {
      setIsUploadingImage(true);
      try {
        const file = await base64ToFile(imagePreview, `performer-${slug}-${Date.now()}.jpg`);
        const filePath = `performers/${slug}/${file.name}`;
        const { error } = await supabase.storage.from("event-images").upload(filePath, file, {
          cacheControl: "3600",
          upsert: true,
        });
        if (error) throw error;
        const { data: urlData } = supabase.storage.from("event-images").getPublicUrl(filePath);
        return urlData.publicUrl;
      } catch (err) {
        console.error("Image upload failed:", err);
        toast({ title: "Greška", description: "Upload slike nije uspio", variant: "destructive" });
        return null;
      } finally {
        setIsUploadingImage(false);
      }
    }
    // URL from imagePreview (e.g. loaded from existing performer)
    if (imagePreview && imagePreview.startsWith("http")) return imagePreview;
    return null;
  };

  const removeImage = () => {
    setImagePreview(null);
    setFormData((prev) => ({ ...prev, image: "" }));
  };

  /** Auto-generate slug and SEO fields when typing name.
   *  - slug: auto only on create
   *  - seo fields: auto only if empty OR if they were previously auto-generated
   *    (meaning: don't overwrite user's manual edits)
   */
  const handleNameChange = (value: string) => {
    setFormData((prev) => {
      const prevName = prev.name || "";
      const nextName = value;

      const nextSlug = editingPerformer ? prev.slug : generateSlug(value);

      const shouldAutoTitle = !(prev.seo_title || "").trim() || isAutoGeneratedTitle(prev.seo_title || "", prevName);

      const shouldAutoDesc =
        !(prev.seo_description || "").trim() || isAutoGeneratedDesc(prev.seo_description || "", prevName);

      return {
        ...prev,
        name: nextName,
        slug: nextSlug,
        seo_title: shouldAutoTitle ? buildPerformerSeoTitle(nextName) : prev.seo_title,
        seo_description: shouldAutoDesc ? buildPerformerSeoDescription(nextName) : prev.seo_description,
      };
    });
  };

  // ============================================
  // 📝 HANDLE SUBMIT SA PREVODOM I ČIŠĆENJEM STORAGE-A
  // ============================================
  const handleSubmit = async () => {
    if (!formData.name.trim()) {
      toast({
        title: "Greška",
        description: "Ime je obavezno",
        variant: "destructive",
      });
      return;
    }

    // Fallback: never let slug/SEO be empty
    const finalSlug = (formData.slug || "").trim() || generateSlug(formData.name);

    // Upload image if needed
    const imageUrl = await uploadPerformerImage(finalSlug);

    const payload: PerformerInput = {
      ...formData,
      slug: finalSlug,
      image: imageUrl || "",
      type: formData.type || "Izvođač",
      seo_title: (formData.seo_title || "").trim() || buildPerformerSeoTitle(formData.name),
      seo_description: (formData.seo_description || "").trim() || buildPerformerSeoDescription(formData.name),
    };

    try {
      let performerId: number | string | null = null;

      if (editingPerformer) {
        await updateMutation.mutateAsync({ id: editingPerformer.id, ...payload });
        performerId = editingPerformer.id;
        toast({ title: "✅ Uspjeh", description: "Izvođač ažuriran" });
      } else {
        // Kreiraj novog izvođača i dobij ID
        const result = await createMutation.mutateAsync(payload);
        // Ako hook vraća podatke, uzmi ID
        if (result && typeof result === "object" && "id" in result) {
          performerId = result.id;
        } else {
          // Ako ne vraća, probaj naći po slug-u
          const { data: newPerformer } = await supabase
            .from("performers")
            .select("id")
            .eq("slug", payload.slug)
            .single();
          if (newPerformer) performerId = newPerformer.id;
        }
        toast({ title: "✅ Uspjeh", description: "Izvođač kreiran" });
      }

      setIsModalOpen(false);

      // 💾 OČISTI LOKALNI STORAGE NAKON USPJEŠNOG ČUVANJA
      clearFromLocalStorage(STORAGE_KEYS.FORM_DATA);
      clearFromLocalStorage(STORAGE_KEYS.EDITING_PERFORMER);
      clearFromLocalStorage(STORAGE_KEYS.MODAL_OPEN);

      // ============================================
      // 🌐 AUTOMATSKI PREVOD NAKON KREIRANJA/AŽURIRANJA
      // ============================================
      if (performerId) {
        setIsTranslating(true);

        toast({
          title: "🌐 Prevod u toku...",
          description: "Prevodim izvođača na engleski jezik...",
        });

        const translationSuccess = await translatePerformer(performerId);

        setIsTranslating(false);

        if (translationSuccess) {
          toast({
            title: "✅ Prevod završen!",
            description: "Izvođač je preveden na EN",
          });
        } else {
          toast({
            title: "⚠️ Prevod nije uspio",
            description: "Izvođač je sačuvan ali nije preveden",
            variant: "destructive",
          });
        }
      }
      // ============================================
    } catch (error: any) {
      toast({
        title: "Greška",
        description: error.message || "Došlo je do greške",
        variant: "destructive",
      });
    }
  };

  const handleDelete = async () => {
    if (!deletingPerformer) return;
    try {
      await deleteMutation.mutateAsync(deletingPerformer.id);
      toast({ title: "Uspjeh", description: "Izvođač obrisan" });
      setIsDeleteDialogOpen(false);
      setDeletingPerformer(null);
    } catch (error: any) {
      toast({
        title: "Greška",
        description: error.message || "Došlo je do greške",
        variant: "destructive",
      });
    }
  };

  const isMutating = createMutation.isPending || updateMutation.isPending || deleteMutation.isPending || isTranslating || isUploadingImage;

  // Klasa za input tekst - bijela u dark mode
  const inputTextClass = "text-gray-900 dark:text-white";

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-purple-500 flex items-center justify-center">
            <Users className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-[#1a1f36] dark:text-white">Izvođači</h1>
            <p className="text-sm text-[#697386] dark:text-gray-400">
              Upravljanje izvođačima i grupama
              {isTranslating && (
                <span className="ml-2 text-blue-600 inline-flex items-center gap-1">
                  <Languages className="w-3 h-3 animate-pulse" />
                  Prevod...
                </span>
              )}
            </p>
          </div>
        </div>
        <Button onClick={handleOpenCreate} className="bg-purple-600 hover:bg-purple-700" disabled={isTranslating}>
          <Plus className="w-4 h-4 mr-2" />
          Dodaj izvođača
        </Button>
      </div>

      {/* Search */}
      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#697386]" />
        <Input
          placeholder="Pretraži izvođače..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className={`pl-10 ${inputTextClass}`}
        />
      </div>

      {/* List */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-8 h-8 animate-spin text-purple-600" />
        </div>
      ) : filteredPerformers.length === 0 ? (
        <div className="text-center py-12 text-[#697386] dark:text-gray-400">
          {searchQuery ? "Nema rezultata pretrage" : "Nema izvođača. Dodajte prvog!"}
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredPerformers.map((performer) => {
            const TypeIcon = getTypeIcon(performer.type);
            return (
              <div
                key={performer.id}
                className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4 flex items-center gap-4 hover:shadow-md transition-shadow"
              >
                {/* Image */}
                <div className="w-16 h-16 rounded-lg bg-gray-100 dark:bg-gray-700 overflow-hidden flex-shrink-0">
                  {performer.image ? (
                    <img src={performer.image} alt={performer.name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <TypeIcon className="w-6 h-6 text-gray-400" />
                    </div>
                  )}
                </div>

                {/* Info */}
                <div className="flex-1 min-w-0">
                  <h3 className="font-semibold text-[#1a1f36] dark:text-white truncate">{performer.name}</h3>
                  <div className="flex items-center gap-2 mt-0.5">
                    <TypeIcon className="w-3 h-3 text-[#697386] dark:text-gray-400" />
                    <span className="text-xs text-[#697386] dark:text-gray-400">{performer.type || "Izvođač"}</span>
                    {(performer as any).name_en && <span className="text-xs text-blue-600">🌐 EN</span>}
                  </div>
                  <p className="text-sm text-[#697386] dark:text-gray-400 truncate">/{performer.slug}</p>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-2">
                  <Link
                    to={`/izvodjaci/${performer.slug}`}
                    target="_blank"
                    className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-[#697386] dark:text-gray-400 hover:text-purple-600"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </Link>
                  <button
                    onClick={() => handleOpenEdit(performer)}
                    className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-[#697386] dark:text-gray-400 hover:text-purple-600"
                    disabled={isTranslating}
                  >
                    <Edit className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleOpenDelete(performer)}
                    className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-[#697386] dark:text-gray-400 hover:text-red-600"
                    disabled={isTranslating}
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Create/Edit Modal */}
      <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              {editingPerformer ? "Uredi izvođača" : "Novi izvođač"}
              <span className="text-xs text-blue-600 font-normal flex items-center gap-1">
                <Languages className="w-3 h-3" />
                Auto-prevod
              </span>
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div>
              <Label htmlFor="name">Ime *</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => handleNameChange(e.target.value)}
                placeholder="Naziv izvođača"
                className={inputTextClass}
              />
            </div>

            <div>
              <Label htmlFor="type">Tip izvođača</Label>
              <select
                id="type"
                value={formData.type || "Izvođač"}
                onChange={(e) => setFormData((prev) => ({ ...prev, type: e.target.value }))}
                className={`w-full h-10 px-3 rounded-md border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring ${inputTextClass}`}
              >
                {PERFORMER_TYPES.map((t) => (
                  <option key={t.value} value={t.value}>
                    {t.label}
                  </option>
                ))}
              </select>
              <p className="text-xs text-[#697386] dark:text-gray-400 mt-1">
                Tip određuje ikonicu koja se prikazuje uz izvođača
              </p>
            </div>

            <div>
              <Label htmlFor="slug">Slug</Label>
              <Input
                id="slug"
                value={formData.slug}
                onChange={(e) => setFormData((prev) => ({ ...prev, slug: e.target.value }))}
                placeholder="url-slug"
                className={inputTextClass}
              />
            </div>

            <div>
              <Label>Slika</Label>
              {!imagePreview ? (
                <div className="border-2 border-dashed border-gray-200 dark:border-gray-600 rounded-xl p-6 text-center hover:border-purple-300 bg-gray-50/50 dark:bg-gray-800/50">
                  <input
                    type="file"
                    accept="image/jpeg,image/png,image/webp,image/gif"
                    onChange={handleImageFileChange}
                    className="hidden"
                    id="performer-img-upload"
                  />
                  <label htmlFor="performer-img-upload" className="cursor-pointer">
                    <Upload className="mx-auto h-8 w-8 text-gray-400 mb-2" />
                    <span className="text-sm font-medium text-gray-600 dark:text-gray-300 block">Kliknite za upload</span>
                    <span className="text-xs text-gray-400">JPG, PNG, WebP, GIF — Max 5MB</span>
                  </label>
                </div>
              ) : (
                <div className="relative mt-1">
                  <img src={imagePreview} alt="Preview" className="w-full h-40 object-cover rounded-lg" />
                  <button
                    type="button"
                    onClick={removeImage}
                    className="absolute top-2 right-2 p-1.5 bg-red-500 text-white rounded-full hover:bg-red-600"
                  >
                    <X className="w-4 h-4" />
                  </button>
                  {imagePreview.startsWith("data:") && (
                    <div className="absolute bottom-2 left-2 bg-green-500 text-white text-xs px-2 py-1 rounded-full flex items-center gap-1">
                      <Check size={12} />
                      Spremno za upload
                    </div>
                  )}
                </div>
              )}
              <div className="mt-3">
                <Input
                  type="url"
                  value={formData.image || ""}
                  onChange={(e) => {
                    setFormData((prev) => ({ ...prev, image: e.target.value }));
                    if (e.target.value) setImagePreview(e.target.value);
                  }}
                  placeholder="Ili unesite URL slike"
                  className={inputTextClass}
                  disabled={!!imagePreview && imagePreview.startsWith("data:")}
                />
              </div>
            </div>

            <div>
              <Label htmlFor="biography">Biografija</Label>
              <Textarea
                id="biography"
                value={formData.biography || ""}
                onChange={(e) => setFormData((prev) => ({ ...prev, biography: e.target.value }))}
                placeholder="Kratka biografija..."
                rows={4}
                className={inputTextClass}
              />
            </div>

            <div>
              <Label htmlFor="seo_title">SEO Naslov</Label>
              <Input
                id="seo_title"
                value={formData.seo_title || ""}
                onChange={(e) => setFormData((prev) => ({ ...prev, seo_title: e.target.value }))}
                placeholder="SEO naslov za pretraživače"
                className={inputTextClass}
              />
            </div>

            <div>
              <Label htmlFor="seo_description">SEO Opis</Label>
              <Textarea
                id="seo_description"
                value={formData.seo_description || ""}
                onChange={(e) => setFormData((prev) => ({ ...prev, seo_description: e.target.value }))}
                placeholder="SEO opis za pretraživače"
                rows={2}
                className={inputTextClass}
              />
            </div>

            {/* Auto SEO button */}
            <div className="pt-2">
              <Button
                type="button"
                variant="outline"
                onClick={() =>
                  setFormData((prev) => ({
                    ...prev,
                    seo_title: buildPerformerSeoTitle(prev.name),
                    seo_description: buildPerformerSeoDescription(prev.name),
                  }))
                }
              >
                Generiši SEO automatski
              </Button>
              <p className="text-xs text-[#697386] dark:text-gray-400 mt-2">
                Automatski popunjava SEO naslov i opis na osnovu imena (etickets fokus). Ručno uređivanje i dalje ostaje
                moguće.
              </p>
            </div>

            {/* Info o auto-prevodu */}
            <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
              <p className="text-xs text-blue-700 dark:text-blue-300 flex items-center gap-2">
                <Languages className="w-4 h-4" />
                Izvođač će biti automatski preveden na engleski nakon čuvanja
              </p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setIsModalOpen(false)} disabled={isMutating}>
              Otkaži
            </Button>
            <Button onClick={handleSubmit} disabled={isMutating} className="bg-purple-600 hover:bg-purple-700">
              {isMutating && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              {isTranslating ? (
                <>
                  <Languages className="w-4 h-4 mr-2 animate-pulse" />
                  Prevod...
                </>
              ) : editingPerformer ? (
                "Sačuvaj"
              ) : (
                "Kreiraj"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Obriši izvođača?</AlertDialogTitle>
            <AlertDialogDescription>
              Da li ste sigurni da želite obrisati izvođača "{deletingPerformer?.name}"? Ova akcija se ne može
              poništiti.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Otkaži</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} className="bg-red-600 hover:bg-red-700">
              {deleteMutation.isPending && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              Obriši
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

export default AdminPerformers;
